version: '3.4'

services:
  fut5api:
    image: fut5api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5110:5110
    volumes:
        - "C:/Code/Fut5_docker/fut5Api:/data"
