# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  fut5api:
    image: fut5api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5110:5110
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
